PREFIX d2sgeneric: <http://data2services/data/emonet/ncats/preppi/preppi_final600.tsv/>
PREFIX d2smodel: <http://data2services/model/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bl: <http://w3id.org/biolink/vocab/>
PREFIX w3idvocab: <https://w3id.org/data2services/vocab/>
INSERT
{
  GRAPH <?_outputGraph> {  
   ?protUri a bl:Protein . 
   ?pathwayUri a bl:Pathway . 

   ?interactionUri a bl:MacromolecularMachineToBiologicalProcessAssociation ;
            bl:relation bl:interacts_with ;
            bl:macromolecular_machine_to_biological_process_association_subject ?uniprotUri1 ;
            bl:macromolecular_machine_to_biological_process_association_object ?uniprotUri2 ;
            bl:has_confidence_level ?ConfidenceLevelStrScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelProtpepScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelStrMaxScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelRedScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelOrtScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelPhyScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelCoexpScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelGoScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelExpScoreUri ;
            bl:has_confidence_level ?ConfidenceLevelFinalScoreUri .

    ?ConfidenceLevelStrScoreUri a bl:ConfidenceLevel ;
            bl:id "str_score" ;
            bl:name "Str score" ;
            bl:node_property ?str_score .

    ?ConfidenceLevelProtpepScoreUri a bl:ConfidenceLevel ;
            bl:id "protpep_score" ;
            bl:name "Protpep score" ;
            bl:node_property ?protpep_score .

    ?ConfidenceLevelStrMaxScoreUri a bl:ConfidenceLevel ;
            bl:id "str_max_score" ;
            bl:name "Str Max score" ;
            bl:node_property ?str_max_score .

    ?ConfidenceLevelRedScoreUri a bl:ConfidenceLevel ;
            bl:id "red_score" ;
            bl:name "Red score" ;
            bl:node_property ?red_score .

    ?ConfidenceLevelOrtScoreUri a bl:ConfidenceLevel ;
            bl:id "ort_score" ;
            bl:name "Ort score" ;
            bl:node_property ?ort_score .

    ?ConfidenceLevelPhyScoreUri a bl:ConfidenceLevel ;
            bl:id "phy_score" ;
            bl:name "Phy score" ;
            bl:node_property ?phy_score .

    ?ConfidenceLevelCoexpScoreUri a bl:ConfidenceLevel ;
            bl:id "coexp_score" ;
            bl:name "Coexp score" ;
            bl:node_property ?coexp_score .

    ?ConfidenceLevelGoScoreUri a bl:ConfidenceLevel ;
            bl:id "go_score" ;
            bl:name "Go score" ;
            bl:node_property ?go_score .

    ?ConfidenceLevelTotalScoreUri a bl:ConfidenceLevel ;
            bl:id "total_score" ;
            bl:name "Total score" ;
            bl:node_property ?total_score .

    ?ConfidenceLevelExpScoreUri a bl:ConfidenceLevel ;
            bl:id "exp_score" ;
            bl:name "Exp score" ;
            bl:node_property ?exp_score .

    ?ConfidenceLevelFinalScoreUri a bl:ConfidenceLevel ;
            bl:id "final_score" ;
            bl:name "Final score" ;
            bl:node_property ?final_score .

 }
}
WHERE {
  SERVICE <?_serviceUrl>  {
    GRAPH <?_inputGraph> {
      ?s d2smodel:Gpcruniprotid ?protId .
      ?s d2smodel:Pathwaynames ?pathwayName .

      BIND( iri(concat("http://identifiers.org/uniprot/", ?protId ) ) AS ?protUri )
      BIND( iri(concat("https://w3id.org/data2services/data/pathway/", md5(?pathwayName) ) ) AS ?pathwayUri )
      BIND( iri(concat("https://w3id.org/data2services/data/protein/interaction/", concat(?prot1, ?prot2) ) ) AS ?interactionUri )

       OPTIONAL { 
         ?s d2smodel:Str_score ?str_score .
         BIND( iri(concat(str(?interactionUri), "/str_score")) AS ?ConfidenceLevelStrScoreUri)
       } OPTIONAL {
         ?s d2smodel:Protpep_score ?protpep_score .
         BIND( iri(concat(str(?interactionUri), "/protpep_score")) AS ?ConfidenceLevelProtpepScoreUri)
       } OPTIONAL { 
         ?s d2smodel:Str_max_score ?str_max_score .
         BIND( iri(concat(str(?interactionUri), "/str_max_score")) AS ?ConfidenceLevelStrMaxScoreUri)
       } OPTIONAL { 
         ?s d2smodel:Red_score ?red_score .
         BIND( iri(concat(str(?interactionUri), "/red_score")) AS ?ConfidenceLevelRedScoreUri)
       } OPTIONAL { 
         ?s d2smodel:Ort_score ?ort_score .
         BIND( iri(concat(str(?interactionUri), "/ort_score")) AS ?ConfidenceLevelOrtScoreUri)
       } OPTIONAL {
         ?s d2smodel:Phy_score ?phy_score .
         BIND( iri(concat(str(?interactionUri), "/phy_score")) AS ?ConfidenceLevelPhyScoreUri)
       } OPTIONAL {
         ?s d2smodel:Coexp_score ?coexp_score .
         BIND( iri(concat(str(?interactionUri), "/coexp_score")) AS ?ConfidenceLevelCoexpScoreUri)
       } OPTIONAL {
         ?s d2smodel:Go_score ?go_score .
         BIND( iri(concat(str(?interactionUri), "/go_score")) AS ?ConfidenceLevelGoScoreUri)
       } OPTIONAL {
         ?s d2smodel:Total_score ?total_score .
         BIND( iri(concat(str(?interactionUri), "/total_score")) AS ?ConfidenceLevelTotalScoreUri)

       } OPTIONAL {
         ?s d2smodel:Dbs ?dbs . # array separated by ,

       } OPTIONAL {
         ?s d2smodel:Pubs ?pubs . # array
         BIND( if( contains(?pubs, "|"),
              iri(concat("http://identifiers.org/", strbefore(?pubs, "|") ) ) ,
              iri(concat("http://identifiers.org/", ?pubs) ) ) 
         AS ?pubsUri )
       
       } OPTIONAL {
         ?s d2smodel:Exp_score ?exp_score .
         BIND( iri(concat(str(?interactionUri), "/exp_score")) AS ?ConfidenceLevelExpScoreUri)
       } OPTIONAL {
         ?s d2smodel:Final_score ?final_score .
         BIND( iri(concat(str(?interactionUri), "/final_score")) AS ?ConfidenceLevelFinalScoreUri)

  }

  # Avoid taking the first row with columns labels
  FILTER( ?prot1 != "prot1") 
}
}
}