PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX bl: <http://bioentity.io/vocab/>

# /{graph}/{class}/{id}/{property}
select ?graph ?class ?entity ?property ?value
from named <?_graph>
where
{
    GRAPH ?graph
    {
        ?entity a ?_class .
        ?entity a ?class .
        ?entity bl:id ?_id .
        ?entity ?property ?value .
    }
}
