PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX bl: <http://bioentity.io/vocab/>

SELECT ?propertyValue
WHERE 
{
    # Should be a variable (source)
    GRAPH <http://data2services/biolink/drugbank> 
    {
        # Should be a variable (type)
        ?item a bl:Drug .
        # Should be a variable (id)
        ?item bl:id "DB11571" .
        # Should be a variable (property)
        ?item bl:affects ?propertyValue .
    }
}
