PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX idot: <http://identifiers.org/idot/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>

# Add ?classCount
# /explore
SELECT ?source ?graph 
WHERE {
    GRAPH <http://data2services/metadata/datasets>
    {
        ?dataset a dctypes:Dataset ;
            idot:preferredPrefix ?source ;
            dcat:accessURL ?graph .
        ?version dct:isVersionOf ?dataset ; 
            dcat:distribution [ a void:Dataset ] .  
    }
}
