PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select *
where{
    {
        select ?class ?p (count(?class) as ?count)  
        where { 
            ?s a ?class . 
            ?s ?p ?o .
            
            filter ( isIRI(?o) ) 
        } 
        group by ?class ?p
        order by desc(?count)
    }
    
    filter( strstarts(str(?class), "http://bioentity.io/vocab/") && strstarts(str(?p), "http://bioentity.io/vocab/")) .
    
    optional {
        ?class rdfs:label ?label .
    }
    
    optional {
        ?p rdfs:label ?predicateLabel .
    }
}