PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# /explore/{graph}/properties/{class}
select ?graph ?class ?classLabel ?property ?propertyLabel ?count 
from named <?_graph> # Remove it to get for all graphs
where{
    {
        select ?graph ?class ?property (count(?property) as ?count)
        where { 
            graph ?graph {
                ?s a <?_class> .
                ?s a ?class .

                ?s ?property ?o .
            }
        } 
        group by ?graph ?class ?property
        order by desc(?count)
    }
    
    optional {
        ?class rdfs:label ?classLabel .
    } optional {
        ?property rdfs:label ?propertyLabel .
    }
}
