PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
FROM <?_graph>
WHERE {
    {
        SELECT ?class ?property (count(?class) as ?count)  
        WHERE { 
            ?s a ?class .
            ?s ?property ?o .
        } 
        GROUP BY ?class ?property
        ORDER BY desc(?count)
    }
    
    OPTIONAL {
        ?class rdfs:label ?classLabel .
    } OPTIONAL {
        ?property rdfs:label ?propertyLabel .
    }
}