PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?graph ?class ?classLabel ?count
where{
    {
        select ?graph ?class ?property (count(?class) as ?count)  
        where { 
            graph ?graph {
                ?s a <http://data2services/data/bio2vec/eggnog/NOG.annotations.tsv> .
                ?s a ?class .

                ?s ?property ?o .
            }
            FILTER(?graph = <?_graph>) # Remove it to get for all graphs
        } 
        group by ?graph ?class ?property
        order by desc(?count)
    }
    
    optional {
        ?class rdfs:label ?classLabel .
    } optional {
        ?property rdfs:label ?propertyLabel .
    }
}
