PREFIX bl: <http://w3id.org/biolink/vocab/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX up: <http://purl.uniprot.org/core/> 
PREFIX uniprot: <http://identifiers.org/uniprot/>
INSERT {
    GRAPH <?_outputGraph> {  
        ?uniprotUri a bl:OrganismTaxon ;
            bl:id ?uniprotUri ;
            bl:name ?label ;
            rdfs:subClassOf ?subClassOf .
    }
}
WHERE {
  SERVICE <https://sparql.uniprot.org>  {
    ?uniprotUri a up:Taxon ;
      rdfs:subClassOf ?subClassOf .

    OPTIONAL {
      ?uniprotUri up:scientificName ?label ;
    }
  }
}