PREFIX bl: <http://w3id.org/biolink/vocab/>
PREFIX bp: <http://www.biopax.org/release/biopax-level3.owl#>

INSERT
{
  GRAPH <?_outputGraph> {  
    #?pathwayUri bl:precedes ?nextStepProcess .
    
    ?pathwayStep a bl:BiologicalProcess ; # TODO: Or bl:Association? Atm it is the same type as BiochemicalReaction...
      bl:has_participant ?stepProcess ; # e.g. BiochemicalReaction and Catalysis
      bl:precedes ?nextPathwayStep ;
      bl:part_of ?pathwayUri .
 }
}
WHERE {
  SERVICE <?_serviceUrl>  {
    GRAPH <?_inputGraph> {
    #GRAPH <http://pathwaycommons.org/pc2/graph> {

      ?pathwayUri a bp:Pathway ;
        bp:dataSource <http://pathwaycommons.org/pc2/#reactome> .
      ?pathwayUri bp:pathwayOrder ?pathwayStep . # Order of processes in pathways
      #?pathwayStep a bp:PathwayStep . # Or use this? But can't filter dataSource

      # A PathwayStep can have multiple stepProcess: bp:BiochemicalReaction and bo:Catalysis for example. And multiple nextSteps
      # http://graphdb.dumontierlab.com/resource?uri=http:%2F%2Fpathwaycommons.org%2Fpc2%2F%23PathwayStep_096ee5f002fa354c8c00e45e09e8547b
      # http://graphdb.dumontierlab.com/resource?uri=http:%2F%2Fpathwaycommons.org%2Fpc2%2F%23PathwayStep_ef1fb101b5a45d37c65550c3ea34dd86
      # In BioLink we need an entity that can combine an association/BiologicalProcess with a catalyser (which can be a BiochemicalReaction also) 
      # that can precedes multiple other steps. I can reuse the PathwayCommons pathwayStep URI
      # Just an bl:Association with catalysis reaction as relation that produces entities? Or something like "upregulate the production of"
      # Or a bl:BiologicalProcess ?

      # Can a PathwayStep be also a bl:Pathway but with a category? Or should it be an association? More like this, 
      # it should be an association included in a pathway in a certain order
      # just a bl:part_of in the BiologicalProcess (formerly PathwayStep) should be good?
      # And then we don't need to add information to point from the bl:Pathway to this pathwayStep
      # the bl:Pathway just holds information about has_participant

      ?pathwayStep bp:stepProcess ?stepProcess .
      OPTIONAL {
        ?pathwayStep bp:nextStep ?nextPathwayStep .
      }
      
      #?nextPathwayStep bp:stepProcess ?nextStepProcess .
    }
  }
}
