# What drugs/compounds target gene products of gene "coagulation factor II, thrombin"?

# 623 results from WikiPathways and DATE

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bl: <http://w3id.org/biolink/vocab/>
SELECT distinct ?gene ?produceProtein ?affectedByDrug ?byRelation ?inInteraction
{
  # Get gene and its product
  #<http://identifiers.org/HGNC:3535> a bl:Gene ;
  ?geneUri a bl:Gene ;
    bl:name "coagulation factor II, thrombin" ;
    bl:has_gene_product ?geneProductUri .
  OPTIONAL {?geneUri bl:name ?gene .}
  ?geneProductUri bl:name ?produceProtein .
    
  # Get associations where drugs affects the gene product
  ?inInteraction ?associationSubject ?geneProductUri ;
   ?associationObject ?drugUri ;
   bl:relation ?byRelation .

  # Get the drug
  ?drugUri a bl:ChemicalSubstance .
  OPTIONAL {?drugUri bl:name ?affectedByDrug .}

#    FILTER(contains(str(?gene), "coagulation factor II, thrombin")) . 
}
# SHOULD GET DRUGBANK
# https://graphdb.dumontierlab.com/resource?uri=https:%2F%2Fw3id.org%2Fdata2services%2Fdata%2Fassociation%2Ftarget%2F881666509406c7ad85ea471cb6812284
